### PR TITLE
Prepare v5.2.0

### PR DESCRIPTION
**Pull request by nikku**
### Proposed Changes

Bumps dependencies + prepares v5.2.0 release. A lot of `fixed upstream` bugs depend on this.

_Search now works reliably, with UX improvements:_

capture o1oRv0_optimized

_Properties panel can now be focused, so undo/redo is possible also outside of inputs:_

capture Mp30XN_optimized

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [x] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by misiekhardcore** [comment]
How do the code reviews working in modeling team? Shouldn't there be at least one approval before merging? Or it depends on the change being made?

**Comment by barmac** [comment]
It depends on the change. I'd rather not yolo-merge features or fixes, but a changelog or dependency update is OK **if you know what you are doing**. Notice that the changes from this PR were already reviewed in the upstream deps' PRs, and also in https://github.com/camunda/camunda-modeler/pull/4711

**Comment by nikku** [comment]
> I'd rather not yolo-merge features or fixes, but a changelog or dependency update is OK if you know what you are doing. 

@misiekhardcore Your merge, your responsibility, and if you mess things up and don't allow others to help / guard you, you gotta do the extra hours to fix it.

**Comment by misiekhardcore** [comment]
> Our world is a little more complex than operate

I don't get this part

**Comment by nikku** [comment]
Sorry, not meant Operate, but _single application_. :slightly_smiling_face: 

For example to implement a feature E2E we need at least 5 PRs, and we try to carefully balance to meet both "work flows" and "4 eyes principle" criteria.

**Comment by misiekhardcore** [comment]
Maybe the reviewing process can be somehow improved if it is a bottleneck right now. I mean for this kind of changes then maybe it is fine to just merge the PR if you know what you are doing, but in general maybe there is something we can improve to minimise the amount of PRs we have to merge before they get a review? Or I am just overthinking this?

**Comment by barmac** [comment]
@misiekhardcore @nikku Let's discuss it outside of this PR as it's unrelated.
We could have an issue in https://github.com/bpmn-io/internal-docs for an async proposal, or an additional topic in [the weekly](https://github.com/bpmn-io/internal-docs/issues/1096) for sync discussion.

**Pull request merged**
