### PR TITLE
Migrate to `npm@8` + housekeeping

### LINKED ISSUE #149: Executable checkbox disables after deleting diagram with pool
__Describe the Bug__
After deleting the last pool with a working diagram in the WebModeler, the "executable" checkbox is automatically disabled and stays disabled even after creating an error-free diagram after that.

__Steps to Reproduce__
[Recording](https://camunda.zoom.us/rec/share/h4dGA-CwwBH2yDd7zk-tP1YsMkYZ380nxMV4i0DfK8QXGFS7apPuH7pCTXXGKxNn.tXcc6rugO7gZ8ZK-?startTime=1658740206000)
Passcode: c@4R?Sp*

1. Create a working diagram in a pool
2. Delete pool 
3. Checkbox "executable" is disabled and stays disabled even when users create a new working, error-free diagram.

__Expected Behavior__
Users would expect the executable checkbox to be automatically enabled again when creating a new diagram, with or without a pool.

__Environment__
WebModeler
- OS: [e.g. MacOS 10.2, Windows 10]
- Modeler version: [e.g. 2.0.0]

### LINKED ISSUE #158: Migrate to `npm@8`
__What should we do?__

Migrate this project to `npm@8`.

__Why should we do it?__

Related to https://github.com/bpmn-io/internal-docs/issues/482

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #149 
Closes #158 
Related to https://github.com/bpmn-io/internal-docs/issues/627

----

* replace `istanbul-instrumenter-loader`
* bump dependencies
* support `npm@8`
* incoorporate `zeebe:properties` support

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
This needs updating the `camunda-bpmn-js-behaviors` dependency in the properties panel (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/pull/746).

**Comment by pinussilvestrus** [comment]
This should be ready for review now.

**Comment by nikku** [comment]
Let's not [back and force between npm@8 and npm@8](https://github.com/camunda/camunda-bpmn-js/pull/159/commits/42261a2d11861c05f8bf4021f9021990eb50eb20) :wink:

**Comment by nikku** [comment]
Fixed via https://github.com/camunda/camunda-bpmn-js/pull/159/commits/a31101d93112739d0b6e88417a91bfa17a10e1f1.

**Comment by pinussilvestrus** [comment]
Woopsie 😅

**Comment by pinussilvestrus** [comment]
Seems like something went wrong with the lockfile

```text
> Run npm ci
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's browserslist@[4](https://github.com/camunda/camunda-bpmn-js/runs/8155873252?check_suite_focus=true#step:5:5).1[7](https://github.com/camunda/camunda-bpmn-js/runs/8155873252?check_suite_focus=true#step:5:8).0 does not satisfy browserslist@4.21.3
```

Pushed the missing changes via https://github.com/camunda/camunda-bpmn-js/pull/159/commits/9650e36a02c44e5430b82a9beb347827be5ef947.

**Review by nikku — APPROVED** [review]
Great stuff! I did give it a smoke test to verify it works.

* `zebee:property` binding
* bug fixes (`zeebe:header` only templated when non-empty)

**Pull request merged**
