### PR TITLE
chore(CHANGELOG): update to v0.13.0

### PR DESCRIPTION
**Pull request by philippfromme**
# Changes

* `FEAT`: add viewer distributions ([#115](https://github.com/camunda/camunda-bpmn-js/pull/115))
* `CHORE`: import behaviors from camunda-bpmn-js-behaviors ([#116](https://github.com/camunda/camunda-bpmn-js/pull/116))
* `DEPS`: update to `bpmn-js-disable-collapsed-subprocess@0.1.4` ([#112](https://github.com/camunda/camunda-bpmn-js/pull/112))
* `DEPS`: update to `bpmn-js-properties-panel@1.1.0` ([03b659](https://github.com/camunda/camunda-bpmn-js/pull/123/commits/03b659da729364abf97ccc2dba421d83e9f5c48e))

### CODE REVIEW

**Comment by barmac** [comment]
Are we ready to release 0.13.0 (stable) with bpmn-js-properties-panel@1.0.0 instead?

**Comment by philippfromme** [comment]
@barmac We'd need to discuss the requirements for going stable with this. Maybe we could.

**Comment by barmac** [comment]
I mean we are still in 0.x phase, so it's expected to have breaking changes later.

**Comment by philippfromme** [comment]
@barmac I changed it to v0.13.0. 🤞🏻

**Comment by barmac** [comment]
Let's update the properties panel in deps and peerdeps too :)

**Comment by philippfromme** [comment]
Will include `bpmn-js-properties-panel@1.1.0` (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/pull/672).

**Comment by philippfromme** [comment]
Added the latest `bpmn-js-properties-panel`. Ready to fly. 🛫

**Review by barmac — APPROVED** [review]
LGTM

**Pull request merged**
