### PR TITLE
deps: update diagram-js-minimap to v4.0.1

### PR DESCRIPTION
**Pull request by philippfromme**
Adds touch support to the minimap (cf. https://github.com/bpmn-io/diagram-js-minimap/pull/54).

### CODE REVIEW

**Comment by nikku** [comment]
I'd say yes. Move it to a normal dependency, and re-release a patch.

**Comment by philippfromme** [comment]
> I'd say yes. Move it to a normal dependency, and re-release a patch.

Okay, will do!

**Comment by philippfromme** [comment]
@nikku I updated the pull request to update the dependency to `diagram-js-minimap@4.0.1`.

**Comment by nikku** [comment]
Perfect. You can see from the PR how natural de-duplication happens :fireworks:

**Pull request merged**
