### PR TITLE
chore(CHANGELOG): update to v0.13.0-alpha.6

### PR DESCRIPTION
**Pull request by philippfromme**
# Changes

## 0.13.0-alpha.6

* `FIX`: set $parent when creating zeebe:CalledElement element ([#99](https://github.com/camunda/camunda-bpmn-js/pull/99))
* `DEPS`: update to `@bpmn-io/properties-panel@0.13.1`
* `DEPS`: update to `bpmn-js-properties-panel@1.0.0-alpha.9`

# Properties Panel

* `FEAT`: allow showing entries and errors through events ([#137](https://github.com/bpmn-io/properties-panel/pull/137))
* `FEAT`: allow opening groups per default ([#139](https://github.com/bpmn-io/properties-panel/pull/139))
* `FEAT`: add documentation ref ([#141](https://github.com/bpmn-io/properties-panel/pull/141))
* `FEAT`: add show callbacks to show entries and errors ([#601](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/601))
* `FEAT`: open element template custom groups ([#621](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/621))
* `FEAT`: display template name in header ([#627](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/627))
* `FEAT`: add documentation ref to header ([#629](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/629))
* `FIX`: copy versioned element template ([#632](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/632))

---

Required by https://github.com/camunda/camunda-modeler/pull/2861

### CODE REVIEW

**Comment by philippfromme** [comment]
I forgot to include the properties panel dependencies.

**Comment by philippfromme** [comment]
> I forgot to include the properties panel dependencies.

Done. ✅

**Comment by nikku** [comment]
Related to https://github.com/bpmn-io/internal-docs/issues/498#issuecomment-1078867702, does it make sense to mirror the crucial changes incorporated via the dependency bumps in the CHANGELOG? 

Assuming here that who reads this wants to get an executive summary on _everything_ that is inside, and not dive into individual component changelogs.

**Comment by philippfromme** [comment]
> Assuming here that who reads this wants to get an executive summary on _everything_ that is inside, and not dive into individual component changelogs.

Done. Can you have a look?

**Comment by nikku** [comment]
Looks great :lipstick:

**Comment by philippfromme** [comment]
CI is still getting its 💩 together.

**Pull request merged**
