### PR TITLE
Refactor Behaviors to Not Monkey Patch

### PR DESCRIPTION
**Pull request by philippfromme**
Preparations for moving the behaviors to a different place. No functionality was changed, only fixed if necessary.

### Fixes

* behaviors use commands instead of monkey patching

### Refactorings

* streamline comments
* drop inherits helper
* assign uppercase IDs to new user task forms
* tests use command stack to test undo/redo
* access business object properties using getters
* code style
* refactor helpers

---

Related to https://github.com/bpmn-io/internal-docs/issues/358
Closes https://github.com/camunda/camunda-bpmn-js/issues/53

### CODE REVIEW

**Comment by barmac** [comment]
> This branch has conflicts that must be resolved

Let's solve it first and then I can do a review.

**Comment by nikku** [comment]
Tests are failing, likely due to merge issues with https://github.com/camunda/camunda-bpmn-js/pull/60?

**Comment by philippfromme** [comment]
Ready to be reviewed.

**Comment by nikku** [comment]
I like moving away from monkey-patching to make these behaviors a little bit more predictable. Maybe you can :zap: talk this one in one of the next hours of code?

**Review by nikku — APPROVED** [review]

**Pull request merged**
